version: '3'
services:
  lugrec:
    container_name: lugrec
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    networks:
      - mynet
networks:
  mynet:
    name: mynet
    external: true
